apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-python-chart.fullname" . }}-config
  labels:
    {{- include "app-python-chart.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-python-chart.fullname" . }}-env
  labels:
    {{- include "app-python-chart.labels" . | nindent 4 }}
data:
  APP_ENV: "dev"
  APP_NAME: "devops-info-service"
  FEATURE_VISITS_COUNTER: "true"
