apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-python-chart.fullname" . }}-secret
  labels:
    {{- include "app-python-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
